version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data/images:/app/data/images
    environment:
      - PYTHONUNBUFFERED=1
  # Note: The Next.js frontend runs in v0 preview. For local dev outside v0,
  # you could add a frontend service/container as needed.
